//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public Conference()
        {
            this.Papers = new HashSet<Paper>();
        }
    
        public int ConferenceID { get; set; }
        public string Title { get; set; }
        public string Acronym { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> PrimaryAreaID { get; set; }
        public Nullable<int> SecondaryAreaID { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string Organizer { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ResearchArea ResearchArea { get; set; }
        public virtual ResearchArea ResearchArea1 { get; set; }
        public virtual ICollection<Paper> Papers { get; set; }
    }
}
