//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchArea
    {
        public ResearchArea()
        {
            this.Conferences = new HashSet<Conference>();
            this.Conferences1 = new HashSet<Conference>();
            this.Papers = new HashSet<Paper>();
            this.Papers1 = new HashSet<Paper>();
        }
    
        public int AreaID { get; set; }
        public string AreaName { get; set; }
    
        public virtual ICollection<Conference> Conferences { get; set; }
        public virtual ICollection<Conference> Conferences1 { get; set; }
        public virtual ICollection<Paper> Papers { get; set; }
        public virtual ICollection<Paper> Papers1 { get; set; }
    }
}
